# Generated by Django 5.1.6 on 2025-02-16 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('fitness_goal', models.CharField(help_text='e.g., lose weight, gain muscle', max_length=100)),
                ('diabetes', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('high_cholesterol', models.BooleanField(default=False)),
                ('arthritis', models.BooleanField(default=False)),
                ('dietary_preference', models.CharField(choices=[('vegan', 'Vegan'), ('gluten_free', 'Gluten Free'), ('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian')], default='non_vegetarian', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
