# Generated by Django 5.1.6 on 2025-02-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_healthprofile_delete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofile',
            name='fitness_goal',
        ),
    ]
