# Generated by Django 5.1.6 on 2025-03-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_healthprofile_fitness_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofile',
            name='arthritis',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='heart_disease',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='high_cholesterol',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='hypertension',
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='health_conditions',
            field=models.TextField(blank=True, help_text='Comma-separated list of health conditions, e.g., diabetes, hypertension', null=True),
        ),
    ]
