# Generated by Django 5.1.6 on 2025-03-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_healthprofile_arthritis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='weight_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
