# Generated by Django 5.1.6 on 2025-04-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.feedback'),
        ),
    ]
